# Generated by Django 3.1.3 on 2021-01-06 16:48

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_customer', models.BooleanField(default=False)),
                ('is_mediator', models.BooleanField(default=False)),
                ('phonenumber', models.PositiveIntegerField(blank=True, default=9059762161, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='India', max_length=256)),
                ('profile_pic', models.ImageField(blank=True, upload_to='customer_profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediatorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='India', max_length=256)),
                ('department', models.CharField(blank=True, choices=[('', ''), ('Regional Transport Office', 'Regional Transport Office'), ('Mandal Revenue Office', 'Mandal Revenue Office'), ('Mandal Development Office', 'Mandal Development Office'), ('Roads and Buildings Department', 'Roads and Buildings Department'), ('BANKS', 'Banks'), ('Registration Office', 'Registration Office')], default='RTO', max_length=256)),
                ('profile_pic', models.ImageField(blank=True, upload_to='mediator_profile_pics')),
                ('number_of_ratings', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(default=0)),
                ('weekdays', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=56)),
                ('unavailable_days', multiselectfield.db.fields.MultiSelectField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=512, null=True)),
                ('rating', models.SmallIntegerField(choices=[(1, 'very poor'), (2, 'poor'), (3, 'average'), (4, 'good'), (5, 'excellent')], default=0)),
                ('review_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customerinfo')),
                ('mediator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mediatorinfo')),
            ],
        ),
        migrations.CreateModel(
            name='NotAvailableDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('mediator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_available_dates', to='accounts.mediatorinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=560)),
                ('is_customer', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('chats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatmessages', to='accounts.chats')),
            ],
        ),
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('assured_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('request_description', models.CharField(blank=True, max_length=256, null=True)),
                ('reject_description', models.CharField(blank=True, max_length=256, null=True)),
                ('accepted_description', models.CharField(blank=True, max_length=256, null=True)),
                ('customer_seen', models.BooleanField(default=False)),
                ('mediator_seen', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectcustomer', to='accounts.customerinfo')),
                ('mediator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectmediator', to='accounts.mediatorinfo')),
            ],
        ),
        migrations.AddField(
            model_name='chats',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerswhochatted', to='accounts.customerinfo'),
        ),
        migrations.AddField(
            model_name='chats',
            name='mediator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediatorswhochatted', to='accounts.mediatorinfo'),
        ),
    ]
