# Generated by Django 3.1.3 on 2021-01-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
